name: Build Electron App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Atualizado para Node 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          # Não instale windows-build-tools - já está incluído no windows-latest

      - name: Build Electron app
        run: npm run make -- --platform=win32 --arch=x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VisNeed-Windows
          path: out/make/*.exe